export { default as PaginaPanelCliente } from './dashboard'
export { default as PaginaProductos } from './productos'
export { default as PaginaPedidos } from './pedidos'
export { default as PaginaEntregas } from './entregas'
export { default as PaginaNotificaciones } from './notificaciones'
export { default as PaginaPerfilCliente } from './perfil'
export { default as PaginaCarrito } from './carrito'
