steps:
  # Paso 0: Instalar dependencias
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['ci', '--prefix', 'web']

  # Paso 1: Construir (Build)
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build', '--prefix', 'web']
    env:
      - 'VITE_API_URL=$_VITE_API_URL'

  # Paso 2: Desplegar a Firebase (CORREGIDO)
  - name: 'node:20'
    dir: 'web'  # Obliga a Cloud Build a entrar a la carpeta 'web' donde está firebase.json
    entrypoint: 'npx'
    args: ['firebase-tools', 'deploy', '--project', '$PROJECT_ID', '--only', 'hosting']

options:
  logging: CLOUD_LOGGING_ONLY