steps:
  # Paso 0: Instalar dependencias
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['ci', '--prefix', 'web'] # Mantén tu prefix web si así lo tenías

  # Paso 1: Construir (Build)
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build', '--prefix', 'web']
    env:
      - 'VITE_API_URL=$_VITE_API_URL' # Esto inyecta la variable que configuramos

  # Paso 2: Desplegar a Firebase (EL NUEVO CAMBIO)
  - name: 'node:20'
    entrypoint: 'npx'
    args: ['firebase-tools', 'deploy', '--project', '$PROJECT_ID', '--only', 'hosting']

options:
  logging: CLOUD_LOGGING_ONLY