steps:
  # 1. Instalar dependencias (Desde la RAÍZ para que encuentre ../shared)
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['ci', '--prefix', 'web'] # --prefix le dice que el package.json está en web
    
  # 2. Construir la web
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build', '--prefix', 'web']
    env:
      - 'VITE_API_BASE_URL=${_VITE_API_URL}'

  # 3. Desplegar a Firebase
  - name: 'gcr.io/$PROJECT_ID/firebase'
    args: ['deploy', '--project=$PROJECT_ID', '--only=hosting']
    dir: 'web' # Aquí sí entramos a web para desplegar

options:
  logging: CLOUD_LOGGING_ONLY