steps:
  # 1. Instalar dependencias
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['ci'] # 'ci' es mejor que 'install' para entornos limpios
    dir: 'web'   # <--- ESTO ES CLAVE: Entra a la carpeta web

  # 2. Construir la web (Build)
  # Terraform inyectará la variable _VITE_API_URL en el Trigger
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']
    dir: 'web'
    env:
      - 'VITE_API_BASE_URL=${_VITE_API_URL}' # React/Vite leerá esto al compilar

  # 3. Desplegar a Firebase Hosting
  - name: 'gcr.io/$PROJECT_ID/firebase'
    args: ['deploy', '--project=$PROJECT_ID', '--only=hosting']
    dir: 'web' # El firebase.json también debe estar dentro de web o configurado correctamente